name: CI

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Bash linter
      run: sudo apt-get install shellcheck

    - name: Run Bash linter
      run: shellcheck **/*.sh

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Run Terraform fmt
      run: terraform fmt -check -recursive

    - name: Run Terraform validate
      run: terraform validate

    - name: Install Go
      run: sudo apt-get install -y golang-go

    - name: Install tfsec
      run: go install github.com/aquasecurity/tfsec/cmd/tfsec@latest

    - name: Run tfsec to check for security issues in Terraform code
      run: ~/go/bin/tfsec .

    - name: Install bash security linter (devskim)
      run: |
        curl -L "https://github.com/microsoft/DevSkim/releases/latest/download/devskim-linux-x64.zip" -o devskim.zip
        unzip devskim.zip -d devskim
        chmod +x devskim/DevSkim
        sudo mv devskim/DevSkim /usr/local/bin/devskim

    - name: Run DevSkim to check for security issues in Bash code
      run: devskim analyze --output-format sarif > devskim-results.sarif

    - name: Install trufflehog
      run: pip install truffleHog

    - name: Run trufflehog to check for secrets
      run: trufflehog filesystem --json .