name: CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - '*'

jobs:
  validate:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/loonar-morpheus-template:latest
      credentials:
         username: ${{ github.repository_owner }}
         password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Bash linter
      run: shellcheck **/*.sh

    - name: Run Terraform fmt
      run: terraform fmt -check -recursive

    - name: Run Terraform validate
      run: terraform validate

    - name: Run tfsec to check for security issues in Terraform code
      run: tfsec .

    - name: Run trufflehog to check for secrets
      run: trufflehog filesystem --json --repo_path .