name: CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/CI.yml'
      - '**/*.tf'
      - '**/*.sh'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/CI.yml'
      - '**/*.tf'
      - '**/*.sh'

jobs:
  lint-and-validate:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/loonar-morpheus-template:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Bash linter
        run: shellcheck **/*.sh

      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v1

      - name: Run Terraform fmt
        run: terraform fmt -check -recursive

      - name: Run Terraform validate
        run: terraform validate

      - name: Run tfsec to check for security issues in Terraform code
        run: tfsec .

      - name: Run trufflehog to check for secrets
        run: trufflehog filesystem --json --repo_path .