name: Copy Repository to Destination on Release
on:
  release:
    types:
      - created

jobs:
  install-gh-cli:
    runs-on: ubuntu-22.04
    steps:
      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

  check-ci-status:
    runs-on: ubuntu-22.04
    needs: install-gh-cli
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.SOURCE_PAT }}" | gh auth login --with-token
        shell: bash

      - name: Check CI
        run: |
          CI_STATUS=$(gh run list --workflow=CI --branch=main --json status --jq '.[0].status')
          if [ "$CI_STATUS" != "completed" ]; then
            echo "CI workflow is not completed. Exiting..."
            exit 1
          fi
          CI_CONCLUSION=$(gh run list --workflow=CI --branch=main --json conclusion --jq '.[0].conclusion')
          if [ "$CI_CONCLUSION" != "success" ]; then
            echo "CI workflow did not succeed. Exiting..."
            exit 1
          fi

  copy-repo:
    runs-on: ubuntu-22.04
    needs: check-ci-status

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v3
      
      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.SOURCE_PAT }}" | gh auth login --with-token
        shell: bash

      - name: Check if Destination Repository Exists
        id: check_repo
        run: |
          if gh repo view "${{ vars.DESTINATION_ORG }}/$GITHUB_REPOSITORY" > /dev/null 2>&1; then
            echo "repository exists"
            echo "result=repository exists" >> $GITHUB_ENV
          else
            echo "repository does not exist"
            echo "result=repository does not exist" >> $GITHUB_ENV
          fi

      - name: Create Destination Repository if it Doesn't Exist
        if: env.result == 'repository does not exist'
        run: |
          for i in {1..5}; do
            gh repo create "${{ vars.DESTINATION_ORG }}/$GITHUB_REPOSITORY" --private && break || sleep 15
          done

      - name: Create Bare Clone of Source Repository
        run: git clone --bare https://github.com/${{ vars.SOURCE_ORG }}/${{ github.event.repository.name }}.git

      - name: Mirror Push to Destination Repository
        run: |
          cd $GITHUB_REPOSITORY.git
          git push --mirror https://github.com/${{ vars.DESTINATION_ORG }}/$GITHUB_REPOSITORY.git
