name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install

    - name: Run pre-commit
      run: pre-commit run --all-files

  secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install trufflehog
      run: |
        pip install trufflehog

    - name: Scan for secrets
      run: trufflehog filesystem --directory .

  vulnerabilities:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install safety
      run: |
        pip install safety

    - name: Check for vulnerabilities
      run: safety check