name: Publish CI Docker image

on:
  push:
    branches:
      - main
    paths:
      - '.github/Dockerfile'
      - '.github/workflows/publish-ci-image.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write    

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.SOURCE_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .github/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/loonar-morpheus-template:latest