name: Setup Container Access

on:
  create:

jobs:
  grant-container-access:
    runs-on: ubuntu-latest
    # Only run if the repository was created from the template
    if: github.event.repository.is_template == false && github.event.repository.template_repository != null
    
    steps:
      - name: Grant package access
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const org = 'loonar-git';
            const pkg = 'loonar-morpheus-template';
            const repo = context.payload.repository.full_name;
            
            await github.rest.packages.addRepositoryToPackageVisibilityForOrg({
              package_type: 'container',
              package_name: pkg,
              org: org,
              repository: repo,
              visibility: 'read'
            });
            
            console.log(`✅ Granted read access to ${repo} for container package ${pkg}`);