name: Setup Branch Protection

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/validate-directories.yml'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check team membership
        id: check-team
        run: |
          IS_MEMBER=$(gh api /orgs/${{ github.repository_owner }}/teams/devops/memberships/${{ github.actor }} --silent && echo "true" || echo "false")
          echo "is_member=$IS_MEMBER" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - uses: actions/checkout@v4
        if: steps.check-team.outputs.is_member == 'true'
      
      - name: Setup branch protection
        if: steps.check-team.outputs.is_member == 'true'
        run: bash utils/setup_branch_protection.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Permission denied
        if: steps.check-team.outputs.is_member != 'true'
        run: |
          echo "❌ Apenas membros do grupo devops podem executar este workflow"
          exit 1 